/// API Endpoint definition for documentation catalog.
class ApiEndpoint {
  const ApiEndpoint({
    required this.index,
    required this.method,
    required this.path,
    required this.category,
    required this.title,
    required this.description,
    this.requiresAuth = false,
    this.requiresAdmin = false,
    this.headers = const {},
    this.queryParams = const {},
    this.pathParams = const {},
    this.requestBody,
    this.multipartFields = const {},
    required this.responseStatus,
    required this.responseBody,
    this.isMultipart = false,
  });

  final int index;
  final String method;
  final String path;
  final String category;
  final String title;
  final String description;
  final bool requiresAuth;
  final bool requiresAdmin;
  final Map<String, String> headers;
  final Map<String, String> queryParams;
  final Map<String, String> pathParams;
  final String? requestBody;
  final Map<String, String> multipartFields;
  final int responseStatus;
  final String responseBody;
  final bool isMultipart;

  String get formattedIndex => '#${index.toString().padLeft(2, '0')}';

  String get curlExample {
    final buffer = StringBuffer()
      ..write("curl -X $method 'http://localhost:8080$path");
    if (queryParams.isNotEmpty) {
      final q = queryParams.entries.map((e) => '${e.key}=${e.value}').join('&');
      buffer.write('?$q');
    }
    buffer.write("'");

    if (requiresAuth || requiresAdmin) {
      buffer.write(" \\\n  -H 'Authorization: Bearer <YOUR_JWT_TOKEN>'");
    }

    if (!isMultipart && requestBody != null) {
      final escapedBody = requestBody!.replaceAll("'", r"\'");
      buffer
        ..write(" \\\n  -H 'Content-Type: application/json'")
        ..write(" \\\n  -d '$escapedBody'");
    } else if (isMultipart) {
      buffer.write(" \\\n  -H 'Content-Type: multipart/form-data'");
      if (multipartFields.isNotEmpty) {
        for (final entry in multipartFields.entries) {
          buffer.write(" \\\n  -F '${entry.key}=${entry.value}'");
        }
      } else {
        buffer.write(" \\\n  -F 'data=sample'");
      }
    }

    return buffer.toString();
  }
}

/// Catalog of all API endpoints across the Classicale backend.
class ApiCatalog {
  static const List<ApiEndpoint> endpoints = [
    // ── 1. SYSTEM & HEALTH ─────────────────────────────────────────────────────
    ApiEndpoint(
      index: 1,
      method: 'GET',
      path: '/health',
      category: 'System',
      title: 'Server Health Check',
      description: 'Returns server operational status for load balancers and uptime monitoring.',
      responseStatus: 200,
      responseBody: 'OK',
    ),
    ApiEndpoint(
      index: 2,
      method: 'GET',
      path: '/',
      category: 'System',
      title: 'Root Status / Interactive API Explorer',
      description: 'Returns JSON server metadata or interactive HTML API documentation.',
      responseStatus: 200,
      responseBody: '{\n  "status": "ok",\n  "message": "Classicale Backend API is running",\n  "totalEndpoints": 58\n}',
    ),

    // ── 2. USER AUTHENTICATION & PROFILE ───────────────────────────────────────
    ApiEndpoint(
      index: 3,
      method: 'POST',
      path: '/api/user/login',
      category: 'User & Auth',
      title: 'User Login',
      description: 'Authenticates user with registered phone or email and password. Returns JWT access token and user profile.',
      requestBody: '{\n  "phone": "9876543210",\n  "password": "MySecretPassword123!"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Login successful",\n  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",\n  "user": {\n    "_id": "65a8e1b2c3d4e5f6a7b8c9d0",\n    "fName": ["Rahul"],\n    "lName": ["Sharma"],\n    "phone": ["9876543210"],\n    "email": "rahul.sharma@example.com",\n    "role": "user",\n    "userNo": 1001,\n    "isVerified": true,\n    "status": "Active",\n    "tokenVersion": 1\n  }\n}',
    ),
    ApiEndpoint(
      index: 4,
      method: 'POST',
      path: '/api/user/signup',
      category: 'User & Auth',
      title: 'User Signup (Complete Multipart Registration)',
      description: 'Registers a new user with full personal details, address, aadhaar card number, photos, and user category.',
      isMultipart: true,
      headers: {'Content-Type': 'multipart/form-data'},
      multipartFields: {
        'phone': '9876543210',
        'fName': 'Rahul',
        'mName': 'Kumar',
        'lName': 'Sharma',
        'email': 'rahul.sharma@example.com',
        'password': 'MySecretPassword123!',
        'gender': 'Male',
        'DOB': '1995-05-15',
        'occupationId': '65a8e1b2c3d4e5f6a7b8c9d0',
        'country': 'India',
        'state': 'Gujarat',
        'city': 'Ahmedabad',
        'area': 'Navrangpura',
        'street1': '101 Sunshine Complex',
        'street2': 'CG Road',
        'pinCode': '380009',
        'aadharNumber': '123456789012',
        'userCategory': 'dealer',
        'uIdNumber': 'UID-10023',
        'referCode': 'REF9988',
        'profileImage': '@/path/to/profile.jpg',
        'aadhaarFront': '@/path/to/aadhaar_front.jpg',
        'aadhaarBack': '@/path/to/aadhaar_back.jpg',
      },
      requestBody: 'Form Data (Multipart):\n  phone: "9876543210"\n  fName: "Rahul"\n  mName: "Kumar"\n  lName: "Sharma"\n  email: "rahul.sharma@example.com"\n  password: "MySecretPassword123!"\n  gender: "Male"\n  DOB: "1995-05-15"\n  occupationId: "65a8e1b2c3d4e5f6a7b8c9d0"\n  otherOccupationName: ""\n  country: "India"\n  state: "Gujarat"\n  city: "Ahmedabad"\n  area: "Navrangpura"\n  street1: "101 Sunshine Complex"\n  street2: "CG Road"\n  pinCode: "380009"\n  aadharNumber: "123456789012"\n  userCategory: "dealer"\n  uIdNumber: "UID-10023"\n  referCode: "REF9988"\n  profileImage: <Binary JPEG/PNG File>\n  aadhaarFront: <Binary JPEG/PNG File>\n  aadhaarBack: <Binary JPEG/PNG File>',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "User registered successfully. Verification pending by admin.",\n  "userId": "65a8e1b2c3d4e5f6a7b8c9d0"\n}',
    ),
    ApiEndpoint(
      index: 5,
      method: 'POST',
      path: '/api/user/verifyOtpUser',
      category: 'User & Auth',
      title: 'Verify User OTP',
      description: 'Verifies SMS/Admin alphanumeric or numeric OTP for user mobile number.',
      requestBody: '{\n  "phone": "9876543210",\n  "otp": "A4B7C9"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP verified successfully",\n  "isOtpVerified": true\n}',
    ),
    ApiEndpoint(
      index: 6,
      method: 'POST',
      path: '/api/user/resendOtp',
      category: 'User & Auth',
      title: 'Resend User OTP',
      description: 'Triggers SMS OTP resend to user mobile number with rate limit cooldown check.',
      requestBody: '{\n  "phone": "9876543210"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP resent successfully to 9876543210"\n}',
    ),
    ApiEndpoint(
      index: 7,
      method: 'POST',
      path: '/api/user/request-otp',
      category: 'User & Auth',
      title: 'Request OTP from Admin',
      description: 'Dispatches real-time notification to admin to manually generate/approve an OTP.',
      requestBody: '{\n  "phone": "9876543210"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP requested from admin. Please wait for approval."\n}',
    ),
    ApiEndpoint(
      index: 8,
      method: 'POST',
      path: '/api/user/verifyPin',
      category: 'User & Auth',
      title: 'Verify Access PIN Code',
      description: 'Verifies an invitation access pin code assigned to user category for privileged access.',
      requestBody: '{\n  "phone": "9876543210",\n  "pin": "CLASSIC2026"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "PIN verified successfully",\n  "isPinVerified": true\n}',
    ),
    ApiEndpoint(
      index: 9,
      method: 'POST',
      path: '/api/user/createNewPassword',
      category: 'User & Auth',
      title: 'Create New Password',
      description: 'Sets a new account password following successful OTP verification.',
      requestBody: '{\n  "phone": "9876543210",\n  "newPassword": "NewStrongPassword!2026"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Password updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 10,
      method: 'POST',
      path: '/api/user/logout',
      category: 'User & Auth',
      title: 'User Logout',
      description: 'Invalidates active JWT token session and clears server session token.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Logged out successfully"\n}',
    ),
    ApiEndpoint(
      index: 11,
      method: 'GET',
      path: '/api/user/getUserByID',
      category: 'User & Auth',
      title: 'Get Current User Profile',
      description: 'Retrieves complete profile details, signed image URLs, assigned permissions, and verification status.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "user": {\n    "_id": "65a8e1b2c3d4e5f6a7b8c9d0",\n    "fName": ["Rahul"],\n    "mName": ["Kumar"],\n    "lName": ["Sharma"],\n    "phone": ["9876543210"],\n    "email": "rahul.sharma@example.com",\n    "gender": ["Male"],\n    "DOB": ["1995-05-15"],\n    "country": ["India"],\n    "state": ["Gujarat"],\n    "city": ["Ahmedabad"],\n    "area": ["Navrangpura"],\n    "street1": ["101 Sunshine Complex"],\n    "pinCode": ["380009"],\n    "profileImage": ["https://ik.imagekit.io/qa9gwdtkh/profiles/user1.jpg?tr=..."],\n    "role": "user",\n    "userNo": 1001,\n    "isVerified": true,\n    "status": "Active"\n  }\n}',
    ),
    ApiEndpoint(
      index: 12,
      method: 'PUT',
      path: '/api/user/updateUser',
      category: 'User & Auth',
      title: 'Update User Profile (Multipart / JSON)',
      description: 'Updates personal info, address, occupation, and uploads replacement profile or aadhaar photos.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      multipartFields: {
        'fName': 'Rahul',
        'mName': 'Kumar',
        'lName': 'Sharma',
        'gender': 'Male',
        'DOB': '1995-05-15',
        'occupationId': '65a8e1b2c3d4e5f6a7b8c9d0',
        'country': 'India',
        'state': 'Gujarat',
        'city': 'Ahmedabad',
        'area': 'Navrangpura',
        'street1': '101 Sunshine Complex',
        'street2': 'CG Road',
        'pinCode': '380009',
        'profileImage': '@/path/to/new_profile.jpg',
      },
      requestBody: 'Form Data (Multipart):\n  fName: "Rahul"\n  mName: "Kumar"\n  lName: "Sharma"\n  gender: "Male"\n  DOB: "1995-05-15"\n  occupationId: "65a8e1b2c3d4e5f6a7b8c9d0"\n  country: "India"\n  state: "Gujarat"\n  city: "Ahmedabad"\n  area: "Navrangpura"\n  street1: "101 Sunshine Complex"\n  street2: "CG Road"\n  pinCode: "380009"\n  profileImage: <Optional Binary File>\n  aadhaarImage1: <Optional Binary File>\n  aadhaarImage2: <Optional Binary File>',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "User profile updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 13,
      method: 'PUT',
      path: '/api/user/update-device-token',
      category: 'User & Auth',
      title: 'Update FCM Device Token',
      description: 'Registers Firebase Cloud Messaging (FCM) device push token for notifications.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "deviceToken": "e7Y8X...fcm_device_token_string_here"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Device token updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 14,
      method: 'GET',
      path: '/api/user/categories',
      category: 'User & Auth',
      title: 'Public User Categories List',
      description: 'Returns available public user registration categories (e.g. Individual, Authorized Dealer, Broker).',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "data": [\n    {\n      "_id": "65b1c3d4e5f6a7b8c9d01111",\n      "categoryKey": "individual",\n      "label": "Individual User",\n      "requiresAdminVerification": false,\n      "verificationType": "none"\n    },\n    {\n      "_id": "65b1c3d4e5f6a7b8c9d02222",\n      "categoryKey": "dealer",\n      "label": "Authorized Dealer",\n      "requiresAdminVerification": true,\n      "verificationType": "PIN"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 15,
      method: 'GET',
      path: '/api/user/permissions',
      category: 'User & Auth',
      title: 'User Category Permissions',
      description: 'Returns list of read and write product categories allowed for current authenticated user.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "read": ["Cars", "Bikes", "Properties", "Electronics"],\n  "write": ["Cars", "Bikes"]\n}',
    ),
    ApiEndpoint(
      index: 16,
      method: 'GET',
      path: '/api/user/allowed-product-types',
      category: 'User & Auth',
      title: 'Allowed Product Types for Posting',
      description: 'Returns allowed product type ObjectIds for creating listings based on category restrictions.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "allowedProductTypes": [\n    "65a8e1b2c3d4e5f6a7b8c9d1",\n    "65a8e1b2c3d4e5f6a7b8c9d2"\n  ]\n}',
    ),

    // ── 3. PRODUCTS & CLASSIFIEDS ──────────────────────────────────────────────
    ApiEndpoint(
      index: 17,
      method: 'GET',
      path: '/api/products/get-product',
      category: 'Products',
      title: 'Get All Classified Products (Feed & Search)',
      description: 'Fetches paginated products with geo-distance filtering, category sorting, and dynamic attribute filters.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'page': '1', 'limit': '20', 'category': 'Car', 'city': 'Ahmedabad', 'minPrice': '500000', 'maxPrice': '1000000'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "total": 45,\n  "page": 1,\n  "limit": 20,\n  "products": [\n    {\n      "_id": "65a91b2c3d4e5f6a7b8c9d11",\n      "title": "Honda City 2022 VX Petrol",\n      "description": "First owner car in mint condition.",\n      "price": 850000,\n      "categories": "Car",\n      "productType": "65a8e1b2c3d4e5f6a7b8c9d1",\n      "subProductType": "65a8e1b2c3d4e5f6a7b8c9d2",\n      "images": ["https://ik.imagekit.io/qa9gwdtkh/products/car1.jpg?tr=..."],\n      "specs": {\n        "brand": "Honda",\n        "model": "City",\n        "year": 2022,\n        "fuel": "Petrol",\n        "transmission": "Manual",\n        "km_driven": 25000\n      },\n      "location": {\n        "type": "Point",\n        "coordinates": [72.5714, 23.0225]\n      },\n      "cityLatest": "Ahmedabad",\n      "stateLatest": "Gujarat",\n      "createdAt": "2026-08-30T10:00:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 18,
      method: 'GET',
      path: '/api/products/get-product-by-id',
      category: 'Products',
      title: 'Get Product Details by ID',
      description: 'Retrieves full product details including seller contact, dynamic specs, and signed images.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'id': '65a91b2c3d4e5f6a7b8c9d11'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "product": {\n    "_id": "65a91b2c3d4e5f6a7b8c9d11",\n    "title": "Honda City 2022 VX Petrol",\n    "description": "Single owner, showroom maintained.",\n    "price": 850000,\n    "categories": "Car",\n    "specs": {\n      "brand": "Honda",\n      "model": "City",\n      "year": 2022,\n      "fuel": "Petrol",\n      "transmission": "Manual",\n      "km_driven": 25000,\n      "color": "White"\n    },\n    "images": ["https://ik.imagekit.io/..."],\n    "user": {\n      "_id": "65a8e1b2c3d4e5f6a7b8c9d0",\n      "fName": ["Rahul"],\n      "phone": ["9876543210"],\n      "city": ["Ahmedabad"]\n    }\n  }\n}',
    ),
    ApiEndpoint(
      index: 19,
      method: 'POST',
      path: '/api/products/add',
      category: 'Products',
      title: 'Add New Product Listing (Complete Multipart)',
      description: 'Publishes a new classified product with up to 10 photos, dynamic metadata specifications, and GeoJSON coordinates.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      multipartFields: {
        'title': 'Honda City 2022 VX Petrol',
        'description': 'First owner car in mint condition. Complete service records.',
        'price': '850000',
        'categories': 'Car',
        'productType': '65a8e1b2c3d4e5f6a7b8c9d1',
        'subProductType': '65a8e1b2c3d4e5f6a7b8c9d2',
        'specs': '{"brand":"Honda","model":"City","year":2022,"fuel":"Petrol","transmission":"Manual","km_driven":25000,"owners":1,"color":"Pearl White"}',
        'latitude': '23.0225',
        'longitude': '72.5714',
        'areaLatest': 'Navrangpura',
        'cityLatest': 'Ahmedabad',
        'stateLatest': 'Gujarat',
        'countryLatest': 'India',
        'searchTags': 'honda,city,sedan,petrol,manual',
        'images': '@/path/to/car1.jpg',
      },
      requestBody: 'Form Data (Multipart):\n  title: "Honda City 2022 VX Petrol"\n  description: "First owner car in mint condition. Complete service records."\n  price: 850000\n  categories: "Car"\n  productType: "65a8e1b2c3d4e5f6a7b8c9d1"\n  subProductType: "65a8e1b2c3d4e5f6a7b8c9d2"\n  specs: JSON.stringify({\n    "brand": "Honda",\n    "model": "City",\n    "year": 2022,\n    "fuel": "Petrol",\n    "transmission": "Manual",\n    "km_driven": 25000,\n    "owners": 1,\n    "color": "Pearl White"\n  })\n  latitude: 23.0225\n  longitude: 72.5714\n  areaLatest: "Navrangpura"\n  cityLatest: "Ahmedabad"\n  stateLatest: "Gujarat"\n  countryLatest: "India"\n  searchTags: "honda,city,sedan,petrol,manual"\n  images: [<Binary Image 1>, <Binary Image 2>, ... (up to 10)]',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Product created successfully",\n  "productId": "65a91b2c3d4e5f6a7b8c9d11"\n}',
    ),
    ApiEndpoint(
      index: 20,
      method: 'PUT',
      path: '/api/products/update',
      category: 'Products',
      title: 'Update Product Listing',
      description: 'Updates product title, price, description, dynamic specs, and adds/replaces photos.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      multipartFields: {
        'productId': '65a91b2c3d4e5f6a7b8c9d11',
        'title': 'Honda City 2022 VX Petrol (Price Dropped)',
        'price': '820000',
        'description': 'Price dropped for urgent sale. Mint condition.',
        'specs': '{"brand":"Honda","model":"City","year":2022,"fuel":"Petrol","transmission":"Manual","km_driven":25000,"owners":1}',
      },
      requestBody: 'Form Data (Multipart):\n  productId: "65a91b2c3d4e5f6a7b8c9d11"\n  title: "Honda City 2022 VX Petrol (Price Dropped)"\n  price: 820000\n  description: "Price dropped for urgent sale. Mint condition."\n  specs: JSON.stringify({\n    "brand": "Honda",\n    "model": "City",\n    "year": 2022,\n    "fuel": "Petrol",\n    "transmission": "Manual",\n    "km_driven": 25000\n  })\n  images: <Optional New Binary Images>',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Product updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 21,
      method: 'DELETE',
      path: '/api/products/softDelete/:productId/:productType',
      category: 'Products',
      title: 'Soft Delete Product',
      description: 'Marks a product listing as deleted so it no longer appears in feed.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'productId': '65a91b2c3d4e5f6a7b8c9d11', 'productType': 'Car'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Product deleted successfully"\n}',
    ),
    ApiEndpoint(
      index: 22,
      method: 'POST',
      path: '/api/products/favorites',
      category: 'Products',
      title: 'Toggle Favorite Product',
      description: 'Adds or removes a classified listing from user favorites collection.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "productId": "65a91b2c3d4e5f6a7b8c9d11",\n  "modelName": "Car"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Product added to favorites"\n}',
    ),
    ApiEndpoint(
      index: 23,
      method: 'GET',
      path: '/api/products/getFavoriteProduct/:userId',
      category: 'Products',
      title: 'Get User Favorite Products',
      description: 'Retrieves list of all favorite product cards for specified user ID.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'userId': '65a8e1b2c3d4e5f6a7b8c9d0'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "favorites": [\n    {\n      "_id": "65a91b2c3d4e5f6a7b8c9d11",\n      "title": "Honda City 2022 VX Petrol",\n      "price": 850000,\n      "images": ["https://ik.imagekit.io/..."],\n      "cityLatest": "Ahmedabad"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 24,
      method: 'GET',
      path: '/api/products/form-metadata',
      category: 'Products',
      title: 'Get Dynamic Form Metadata',
      description: 'Fetches schema, dynamic input fields, dropdown options, and regex validation rules for posting forms.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'productType': '65a8e1b2c3d4e5f6a7b8c9d1', 'subProductType': '65a8e1b2c3d4e5f6a7b8c9d2'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "fields": [\n    {\n      "key": "fuel_type",\n      "label": "Fuel Type",\n      "type": "dropdown",\n      "options": [\n        { "label": "Petrol", "value": "petrol" },\n        { "label": "Diesel", "value": "diesel" },\n        { "label": "Electric", "value": "electric" },\n        { "label": "CNG", "value": "cng" }\n      ],\n      "isOptional": false,\n      "groupName": "Specifications"\n    },\n    {\n      "key": "transmission",\n      "label": "Transmission",\n      "type": "dropdown",\n      "options": [\n        { "label": "Manual", "value": "manual" },\n        { "label": "Automatic", "value": "automatic" }\n      ],\n      "isOptional": false\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 25,
      method: 'POST',
      path: '/api/products/track-product-view',
      category: 'Products',
      title: 'Track Product View',
      description: 'Increments unique viewer count for a listing.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "productId": "65a91b2c3d4e5f6a7b8c9d11"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "views": 53\n}',
    ),

    // ── 4. BRANDS & MODELS ─────────────────────────────────────────────────────
    ApiEndpoint(
      index: 26,
      method: 'GET',
      path: '/api/brands',
      category: 'Brands & Models',
      title: 'Get Brands for Product Type',
      description: 'Returns list of vehicle or electronics brand names for cascading selectors.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'productType': 'car'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "brands": ["Honda", "Hyundai", "Maruti Suzuki", "Tata", "Toyota", "Mahindra"]\n}',
    ),
    ApiEndpoint(
      index: 27,
      method: 'GET',
      path: '/api/brands/:productType/:brand/models',
      category: 'Brands & Models',
      title: 'Get Models for Brand',
      description: 'Returns all models belonging to a specific brand for cascading selectors.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'productType': 'car', 'brand': 'Honda'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "brand": "Honda",\n  "models": ["City", "Civic", "Amaze", "Elevate", "Jazz", "WR-V"]\n}',
    ),

    // ── 5. REAL-TIME CHAT & MESSAGING ──────────────────────────────────────────
    ApiEndpoint(
      index: 28,
      method: 'POST',
      path: '/api/chat/fetch-exsisting-conversationId',
      category: 'Chat & Messaging',
      title: 'Create or Fetch Conversation ID',
      description: 'Creates a new 1-on-1 buyer-seller conversation or returns existing thread ID.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "sellerId": "65a8e1b2c3d4e5f6a7b8c9d0",\n  "productId": "65a91b2c3d4e5f6a7b8c9d11"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "conversationId": "65b21b2c3d4e5f6a7b8c9d99"\n}',
    ),
    ApiEndpoint(
      index: 29,
      method: 'POST',
      path: '/api/chat/send-message',
      category: 'Chat & Messaging',
      title: 'Send Text Chat Message',
      description: 'Sends text message in conversation and emits real-time WebSocket event.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "chatId": "65b21b2c3d4e5f6a7b8c9d99",\n  "content": "Hi, is this Honda City still available for test drive?",\n  "type": "text",\n  "metaData": {\n    "clientMessageId": "msg-uuid-9988-1234"\n  }\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": {\n    "_id": "65b22b2c3d4e5f6a7b8c9d00",\n    "chatId": "65b21b2c3d4e5f6a7b8c9d99",\n    "senderId": "65a8e1b2c3d4e5f6a7b8c9d0",\n    "content": "Hi, is this Honda City still available for test drive?",\n    "type": "text",\n    "status": "sent",\n    "createdAt": "2026-08-30T11:00:00.000Z"\n  }\n}',
    ),
    ApiEndpoint(
      index: 30,
      method: 'POST',
      path: '/api/chat/sent-image',
      category: 'Chat & Messaging',
      title: 'Send Image Chat Message (Multipart)',
      description: 'Uploads and sends photo attachment in chat with real-time push notification.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      multipartFields: {
        'chatId': '65b21b2c3d4e5f6a7b8c9d99',
        'image': '@/path/to/inspection_photo.jpg',
        'clientMessageId': 'img-uuid-5544-7788',
      },
      requestBody: 'Form Data (Multipart):\n  chatId: "65b21b2c3d4e5f6a7b8c9d99"\n  image: <Binary JPEG/PNG File>\n  clientMessageId: "img-uuid-5544-7788"',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": {\n    "_id": "65b23b2c3d4e5f6a7b8c9d11",\n    "content": "https://ik.imagekit.io/qa9gwdtkh/chat/img1.jpg?tr=...",\n    "type": "image",\n    "status": "sent"\n  }\n}',
    ),
    ApiEndpoint(
      index: 31,
      method: 'GET',
      path: '/api/chat/get-all-messages/:conversationId',
      category: 'Chat & Messaging',
      title: 'Get Conversation Messages',
      description: 'Fetches message history for a conversation thread.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'conversationId': '65b21b2c3d4e5f6a7b8c9d99'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "messages": [\n    {\n      "_id": "65b22b2c3d4e5f6a7b8c9d00",\n      "content": "Hi, is this Honda City still available?",\n      "status": "read",\n      "createdAt": "2026-08-30T11:00:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 32,
      method: 'GET',
      path: '/api/chat/get-all-conversations/:userId',
      category: 'Chat & Messaging',
      title: 'Get User Conversations List',
      description: 'Retrieves active conversation inbox threads with last message preview and unread counts.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'userId': '65a8e1b2c3d4e5f6a7b8c9d0'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "conversations": [\n    {\n      "_id": "65b21b2c3d4e5f6a7b8c9d99",\n      "participants": ["65a8e1b2c3d4e5f6a7b8c9d0", "65a8e1b2c3d4e5f6a7b8c9d9"],\n      "product": { "_id": "65a91...", "title": "Honda City 2022" },\n      "lastMessage": "Hi, is this Honda City still available?",\n      "updatedAt": "2026-08-30T11:30:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 33,
      method: 'PUT',
      path: '/api/chat/update-message-status',
      category: 'Chat & Messaging',
      title: 'Mark Messages as Read',
      description: 'Updates message delivery and read receipts across conversation.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "chatId": "65b21b2c3d4e5f6a7b8c9d99",\n  "status": "read"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Messages marked as read"\n}',
    ),
    ApiEndpoint(
      index: 34,
      method: 'GET',
      path: '/api/chat/unread_message_count',
      category: 'Chat & Messaging',
      title: 'Get Unread Messages Count',
      description: 'Returns total unread chat badge count for user.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "unreadCount": 3\n}',
    ),

    // ── 6. HOME PROMOTIONS & BANNERS ───────────────────────────────────────────
    ApiEndpoint(
      index: 35,
      method: 'GET',
      path: '/api/home/content',
      category: 'Home & Feed',
      title: 'Get Home Content & Active Banners',
      description: 'Returns active promotional banners, categories, and featured products tailored to user permissions.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'city': 'Ahmedabad', 'state': 'Gujarat'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "banners": [\n    {\n      "_id": "65c1b2c3d4e5f6a7b8c9d111",\n      "imageUrl": "https://ik.imagekit.io/qa9gwdtkh/banners/diwali.png?tr=...",\n      "actionType": "CATEGORY",\n      "actionData": "Car",\n      "order": 1\n    }\n  ],\n  "categories": ["Car", "Bike", "Property", "Electronics"]\n}',
    ),
    ApiEndpoint(
      index: 36,
      method: 'POST',
      path: '/api/home/banner/:bannerId/click',
      category: 'Home & Feed',
      title: 'Track Banner Click',
      description: 'Increments banner analytics click count.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'bannerId': '65c1b2c3d4e5f6a7b8c9d111'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Banner click recorded successfully"\n}',
    ),

    // ── 7. SUPPORT & TICKETS ───────────────────────────────────────────────────
    ApiEndpoint(
      index: 37,
      method: 'POST',
      path: '/api/support/create-get-chat',
      category: 'Support & Helpdesk',
      title: 'Create or Get Support Ticket Chat',
      description: 'Opens or returns active support thread between user and customer support staff.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "supportChat": {\n    "_id": "65d1b2c3d4e5f6a7b8c9d222",\n    "userId": "65a8e1b2c3d4e5f6a7b8c9d0",\n    "status": "open",\n    "unreadCount": 0\n  }\n}',
    ),
    ApiEndpoint(
      index: 38,
      method: 'POST',
      path: '/api/support/send-message',
      category: 'Support & Helpdesk',
      title: 'Send Support Message',
      description: 'Sends message or photo attachment to support staff.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "chatId": "65d1b2c3d4e5f6a7b8c9d222",\n  "content": "Hello, I uploaded my Aadhaar card 2 days ago, please check verification status.",\n  "type": "text"\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Support message sent successfully"\n}',
    ),
    ApiEndpoint(
      index: 39,
      method: 'GET',
      path: '/api/support/get-messages/:userId',
      category: 'Support & Helpdesk',
      title: 'Get Support Thread Messages',
      description: 'Retrieves all support messages for a user ticket.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'userId': '65a8e1b2c3d4e5f6a7b8c9d0'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "messages": [\n    {\n      "_id": "65d2b2c3d4e5f6a7b8c9d333",\n      "senderRole": "user",\n      "content": "Hello, please check verification status.",\n      "status": "read",\n      "createdAt": "2026-08-30T12:00:00.000Z"\n    }\n  ]\n}',
    ),

    // ── 8. OTP & PASSWORD MANAGEMENT ───────────────────────────────────────────
    ApiEndpoint(
      index: 40,
      method: 'POST',
      path: '/api/otp/forgot-password',
      category: 'OTP & Password',
      title: 'Forgot Password (Send OTP via SMS)',
      description: 'Dispatches OTP via Fast2SMS/MSG91 to registered mobile number for password recovery.',
      requestBody: '{\n  "phone": "9876543210"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP sent successfully to 9876543210"\n}',
    ),
    ApiEndpoint(
      index: 41,
      method: 'POST',
      path: '/api/otp/verify-otp',
      category: 'OTP & Password',
      title: 'Verify Password Reset OTP',
      description: 'Verifies recovery OTP code.',
      requestBody: '{\n  "phone": "9876543210",\n  "otp": "782190"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP verified successfully"\n}',
    ),
    ApiEndpoint(
      index: 42,
      method: 'POST',
      path: '/api/otp/change-password',
      category: 'OTP & Password',
      title: 'Change Password via Recovery Token',
      description: 'Updates account password with recovery proof.',
      requestBody: '{\n  "phone": "9876543210",\n  "password": "BrandNewPassword!2026"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Password changed successfully"\n}',
    ),

    // ── 9. LOCATION SERVICES ───────────────────────────────────────────────────
    ApiEndpoint(
      index: 43,
      method: 'GET',
      path: '/api/location/locations',
      category: 'Locations',
      title: 'Search Locations & Pincodes',
      description: 'Returns matching postal codes, districts, subdistricts, and states.',
      queryParams: {'search': 'Ahmedabad', 'pincode': '380001'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "locations": [\n    {\n      "Country_Code": "IN",\n      "Postal_Code": "380001",\n      "Location_Name": "Ahmedabad",\n      "District": "Ahmedabad",\n      "State": "Gujarat",\n      "State_Code": "GJ"\n    }\n  ]\n}',
    ),

    // ── 10. APP VERSION & UPDATES ──────────────────────────────────────────────
    ApiEndpoint(
      index: 44,
      method: 'GET',
      path: '/api/app-version/latest',
      category: 'App Updates',
      title: 'Get Latest App Version',
      description: 'Checks for mandatory Flutter mobile app update APK releases.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "data": {\n    "version": "1.0.8",\n    "versionName": "v1.0.8",\n    "apkLink": "https://storage.googleapis.com/classicale-app/app-release-1.0.8.apk",\n    "changes": "1. High-speed Dart Frog backend\\n2. Enhanced search filters\\n3. Bug fixes",\n    "isActive": true\n  }\n}',
    ),

    // ── 11. ABOUT US & GUIDE VIDEOS ────────────────────────────────────────────
    ApiEndpoint(
      index: 45,
      method: 'GET',
      path: '/api/about-us',
      category: 'About & Guide',
      title: 'Get About Us Information',
      description: 'Returns company mission, story, stats, values, and tagline.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "data": {\n    "name": "Classicale",\n    "tag_line": "India\'s Most Trusted Verified Classifieds",\n    "our_mission": "To provide a secure and transparent marketplace for verified buyers and sellers.",\n    "our_story": "Founded in 2026 to revolutionize local commerce with instant verification.",\n    "happy_customer": 25000,\n    "products": 50000,\n    "statisfaction": 98,\n    "our_values": [\n      { "icon": "trust", "title": "Trust", "description": "100% Aadhaar-verified users." },\n      { "icon": "security", "title": "Security", "description": "End-to-end encrypted chats." }\n    ]\n  }\n}',
    ),
    ApiEndpoint(
      index: 46,
      method: 'GET',
      path: '/api/app-guide-video/get-visible-video',
      category: 'About & Guide',
      title: 'Get Active App Guide Video',
      description: 'Returns streaming URL for the active app tutorial video.',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "video": {\n    "title": "How to create a verified listing",\n    "videoName": "app_guide_v1.mp4",\n    "streamUrl": "/public/videos/app-guide/app_guide_v1.mp4",\n    "videoDuration": 120\n  }\n}',
    ),

    // ── 12. FEEDBACK & FEATURE REQUESTS ────────────────────────────────────────
    ApiEndpoint(
      index: 47,
      method: 'POST',
      path: '/api/feedback',
      category: 'Feedback',
      title: 'Submit Feature Request / Feedback',
      description: 'Submits user feedback or feature proposal.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "title": "Add WhatsApp Integration",\n  "description": "Please allow sharing product links directly to WhatsApp with preview image."\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Feature request submitted successfully",\n  "id": "65e1b2c3d4e5f6a7b8c9d444"\n}',
    ),

    // ── 13. ADMIN PANEL & RBAC MANAGEMENT ──────────────────────────────────────
    ApiEndpoint(
      index: 48,
      method: 'POST',
      path: '/api/admin/login',
      category: 'Admin & RBAC',
      title: 'Admin Login',
      description: 'Authenticates superadmin or subadmin and returns admin JWT token with role claims.',
      requestBody: '{\n  "email": "superadmin@classical.com",\n  "password": "SuperSecretAdminPassword!2026"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",\n  "admin": {\n    "_id": "65e1b2c3d4e5f6a7b8c9d000",\n    "username": "Super Administrator",\n    "email": "superadmin@classical.com",\n    "role": "superadmin",\n    "tokenVersion": 1\n  }\n}',
    ),
    ApiEndpoint(
      index: 49,
      method: 'GET',
      path: '/api/admin/get_all_user',
      category: 'Admin & RBAC',
      title: 'Get All Users (Admin Management Table)',
      description: 'Returns paginated user list with status, verification, aadhaar images, and phone numbers.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      queryParams: {'page': '1', 'limit': '50', 'status': 'Active', 'search': 'Rahul'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "total": 1200,\n  "users": [\n    {\n      "_id": "65a8e1b2c3d4e5f6a7b8c9d0",\n      "fName": ["Rahul"],\n      "lName": ["Sharma"],\n      "phone": ["9876543210"],\n      "email": "rahul.sharma@example.com",\n      "isVerified": true,\n      "status": "Active",\n      "userCategory": "dealer",\n      "createdAt": "2026-08-30T09:00:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 50,
      method: 'POST',
      path: '/api/admin/verify_by_admin',
      category: 'Admin & RBAC',
      title: 'Verify or Reject User by Admin',
      description: 'Approves user Aadhaar verification or rejects with reason string.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "userId": "65a8e1b2c3d4e5f6a7b8c9d0",\n  "isVerified": true,\n  "aadhaarRejectionReason": ""\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "User verification status updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 51,
      method: 'POST',
      path: '/api/admin/user_active_inActive',
      category: 'Admin & RBAC',
      title: 'Toggle User Active / Inactive / Suspended',
      description: 'Activates, suspends, or deletes a user account.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "userId": "65a8e1b2c3d4e5f6a7b8c9d0",\n  "status": "Active"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "User status updated to Active"\n}',
    ),
    ApiEndpoint(
      index: 52,
      method: 'POST',
      path: '/api/admin/access_pin',
      category: 'Admin & RBAC',
      title: 'Assign Access PIN to User',
      description: 'Generates and assigns secret PIN to user for special category permissions.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "userId": "65a8e1b2c3d4e5f6a7b8c9d0",\n  "pin": "VIP-2026-8899"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Access PIN assigned successfully"\n}',
    ),
    ApiEndpoint(
      index: 53,
      method: 'GET',
      path: '/api/admin/subadmin/all',
      category: 'Admin & RBAC',
      title: 'Get All Subadmin Staff',
      description: 'Lists all subadmin staff members.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "subadmins": [\n    {\n      "_id": "65f1b2c3d4e5f6a7b8c9d555",\n      "username": "Operations Moderator",\n      "email": "mod.ops@classical.com",\n      "role": "subadmin",\n      "phone": "9822334455"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 54,
      method: 'POST',
      path: '/api/admin/subadmin/create',
      category: 'Admin & RBAC',
      title: 'Create Subadmin with Granular Permissions (Complete Body)',
      description: 'Provisions new subadmin staff with read, write, and assign_pin flags across all 15 modules.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "username": "Operations Moderator",\n  "email": "mod.ops@classical.com",\n  "password": "ModStrongPassword!2026",\n  "fName": "Vikram",\n  "lName": "Patel",\n  "phone": "9822334455",\n  "permissions": {\n    "dashboard": { "read": true, "write": false, "assign_pin": false },\n    "product": { "read": true, "write": true, "assign_pin": false },\n    "user": { "read": true, "write": true, "assign_pin": true },\n    "access_code": { "read": true, "write": true, "assign_pin": true },\n    "reports": { "read": true, "write": true, "assign_pin": false },\n    "chat_reports": { "read": true, "write": true, "assign_pin": false },\n    "app_versions": { "read": true, "write": false, "assign_pin": false },\n    "feature_request": { "read": true, "write": true, "assign_pin": false },\n    "reviews": { "read": true, "write": true, "assign_pin": false },\n    "support_chat": { "read": true, "write": true, "assign_pin": false },\n    "about_us": { "read": true, "write": false, "assign_pin": false },\n    "app_guide": { "read": true, "write": false, "assign_pin": false },\n    "banners": { "read": true, "write": false, "assign_pin": false },\n    "occupation": { "read": true, "write": true, "assign_pin": false },\n    "sub_product_types": { "read": true, "write": true, "assign_pin": false }\n  }\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Subadmin created successfully",\n  "adminId": "65f1b2c3d4e5f6a7b8c9d555"\n}',
    ),
    ApiEndpoint(
      index: 55,
      method: 'GET',
      path: '/api/admin/permissions',
      category: 'Admin & RBAC',
      title: 'Get Admin Permissions Matrix',
      description: 'Returns RBAC granular permissions matrix for logged-in admin.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "permissions": {\n    "dashboard": { "read": true, "write": false, "assign_pin": false },\n    "product": { "read": true, "write": true, "assign_pin": false },\n    "user": { "read": true, "write": true, "assign_pin": true }\n  }\n}',
    ),
    ApiEndpoint(
      index: 56,
      method: 'GET',
      path: '/api/admin/audit-logs',
      category: 'Admin & RBAC',
      title: 'Get Admin Audit Logs',
      description: 'Retrieves audit logs tracking every admin action, endpoint, and modification.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      queryParams: {'page': '1', 'limit': '50', 'action': 'UPDATE'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "logs": [\n    {\n      "_id": "65g1b2c3d4e5f6a7b8c9d666",\n      "adminUsername": "superadmin",\n      "action": "VERIFY_USER",\n      "endpoint": "/api/admin/verify_by_admin",\n      "status": "SUCCESS",\n      "ipAddress": "127.0.0.1",\n      "createdAt": "2026-08-31T07:00:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 57,
      method: 'GET',
      path: '/api/admin/report_product',
      category: 'Admin & RBAC',
      title: 'Get Product Moderation Reports',
      description: 'Lists all user-reported product listings requiring admin review.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "reports": [\n    {\n      "_id": "65h1b2c3d4e5f6a7b8c9d777",\n      "productId": "65a91b2c3d4e5f6a7b8c9d11",\n      "description": "Suspicious fraudulent ad asking for advance payment.",\n      "status": "pending",\n      "createdAt": "2026-08-30T15:00:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 58,
      method: 'PUT',
      path: '/api/admin/update-report-status',
      category: 'Admin & RBAC',
      title: 'Resolve or Decline Product Report',
      description: 'Updates status of moderation report to resolve or decline.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "reportId": "65h1b2c3d4e5f6a7b8c9d777",\n  "status": "resolve",\n  "note": "Product listing removed and seller issued policy warning."\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Report status updated successfully"\n}',
    ),
  ];
}
