/// API Endpoint definition for documentation catalog.
class ApiEndpoint {
  const ApiEndpoint({
    required this.index,
    required this.method,
    required this.path,
    required this.category,
    required this.title,
    required this.description,
    this.requiresAuth = false,
    this.requiresAdmin = false,
    this.headers = const {},
    this.queryParams = const {},
    this.pathParams = const {},
    this.requestBody,
    required this.responseStatus,
    required this.responseBody,
    this.isMultipart = false,
  });

  final int index;
  final String method;
  final String path;
  final String category;
  final String title;
  final String description;
  final bool requiresAuth;
  final bool requiresAdmin;
  final Map<String, String> headers;
  final Map<String, String> queryParams;
  final Map<String, String> pathParams;
  final String? requestBody;
  final int responseStatus;
  final String responseBody;
  final bool isMultipart;

  String get formattedIndex => '#${index.toString().padLeft(2, '0')}';

  String get curlExample {
    final buffer = StringBuffer()
      ..write("curl -X $method 'http://localhost:8080$path");
    if (queryParams.isNotEmpty) {
      final q = queryParams.entries.map((e) => '${e.key}=${e.value}').join('&');
      buffer.write('?$q');
    }
    buffer.write("'");

    if (requiresAuth || requiresAdmin) {
      buffer.write(" \\\n  -H 'Authorization: Bearer <YOUR_JWT_TOKEN>'");
    }

    if (!isMultipart && requestBody != null) {
      final escapedBody = requestBody!.replaceAll("'", r"\'");
      buffer
        ..write(" \\\n  -H 'Content-Type: application/json'")
        ..write(" \\\n  -d '$escapedBody'");
    } else if (isMultipart) {
      buffer
        ..write(" \\\n  -H 'Content-Type: multipart/form-data'")
        ..write(" \\\n  -F 'title=Sample Item'");
    }

    return buffer.toString();
  }
}

/// Catalog of all API endpoints across the Classicale backend.
class ApiCatalog {
  static const List<ApiEndpoint> endpoints = [
    // ── SYSTEM & HEALTH ────────────────────────────────────────────────────────
    ApiEndpoint(
      index: 1,
      method: 'GET',
      path: '/health',
      category: 'System',
      title: 'Server Health Check',
      description: 'Returns server operational status for load balancers and uptime monitoring.',
      responseStatus: 200,
      responseBody: 'OK',
    ),
    ApiEndpoint(
      index: 2,
      method: 'GET',
      path: '/',
      category: 'System',
      title: 'Root Status / Interactive API Docs',
      description: 'Returns JSON server metadata or interactive HTML API documentation.',
      responseStatus: 200,
      responseBody: '{\n  "status": "ok",\n  "message": "Classicale Backend API is running",\n  "version": "1.0.0"\n}',
    ),

    // ── USER AUTHENTICATION & PROFILE ──────────────────────────────────────────
    ApiEndpoint(
      index: 3,
      method: 'POST',
      path: '/api/user/login',
      category: 'User & Auth',
      title: 'User Login',
      description: 'Authenticates user with phone or email and password. Returns JWT access token and user profile.',
      requestBody: '{\n  "phone": "9876543210",\n  "password": "mySecretPassword123"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Login successful",\n  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6...",\n  "user": {\n    "_id": "65a8e1b2c3d4e5f6a7b8c9d0",\n    "fName": ["Rahul"],\n    "lName": ["Sharma"],\n    "phone": ["9876543210"],\n    "role": "user",\n    "userNo": 1001,\n    "isVerified": true\n  }\n}',
    ),
    ApiEndpoint(
      index: 4,
      method: 'POST',
      path: '/api/user/signup',
      category: 'User & Auth',
      title: 'User Signup (Multipart)',
      description: 'Registers a new user with personal details, aadhaar card photos, and profile image.',
      isMultipart: true,
      headers: {'Content-Type': 'multipart/form-data'},
      requestBody: 'Form Data:\n  fName: "Rahul"\n  lName: "Sharma"\n  phone: "9876543210"\n  password: "mySecretPassword123"\n  userCategory: "individual"\n  profileImage: <file>\n  aadhaarFront: <file>\n  aadhaarBack: <file>',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "User registered successfully. Verification pending.",\n  "userId": "65a8e1b2c3d4e5f6a7b8c9d0"\n}',
    ),
    ApiEndpoint(
      index: 5,
      method: 'POST',
      path: '/api/user/verifyOtpUser',
      category: 'User & Auth',
      title: 'Verify User OTP',
      description: 'Verifies SMS/Admin OTP sent to user phone number.',
      requestBody: '{\n  "phone": "9876543210",\n  "otp": "452189"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP verified successfully",\n  "isOtpVerified": true\n}',
    ),
    ApiEndpoint(
      index: 6,
      method: 'POST',
      path: '/api/user/resendOtp',
      category: 'User & Auth',
      title: 'Resend User OTP',
      description: 'Triggers SMS OTP resend to user mobile number with rate limit cooldown.',
      requestBody: '{\n  "phone": "9876543210"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP resent successfully"\n}',
    ),
    ApiEndpoint(
      index: 7,
      method: 'POST',
      path: '/api/user/request-otp',
      category: 'User & Auth',
      title: 'Request OTP from Admin',
      description: 'Sends notification to admin to generate an approval OTP.',
      requestBody: '{\n  "phone": "9876543210"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP requested from admin"\n}',
    ),
    ApiEndpoint(
      index: 8,
      method: 'POST',
      path: '/api/user/verifyPin',
      category: 'User & Auth',
      title: 'Verify Access Pin',
      description: 'Verifies an invitation access pin code assigned to user category.',
      requestBody: '{\n  "phone": "9876543210",\n  "pin": "CLASSIC2026"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "PIN verified successfully"\n}',
    ),
    ApiEndpoint(
      index: 9,
      method: 'POST',
      path: '/api/user/createNewPassword',
      category: 'User & Auth',
      title: 'Create New Password',
      description: 'Sets new password after verified OTP flow.',
      requestBody: '{\n  "phone": "9876543210",\n  "newPassword": "NewStrongPassword!2026"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Password updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 10,
      method: 'POST',
      path: '/api/user/logout',
      category: 'User & Auth',
      title: 'User Logout',
      description: 'Invalidates user session and updates token version.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Logged out successfully"\n}',
    ),
    ApiEndpoint(
      index: 11,
      method: 'GET',
      path: '/api/user/getUserByID',
      category: 'User & Auth',
      title: 'Get Current User Profile',
      description: 'Retrieves profile, signed image URLs, favorites, and permissions of logged-in user.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "user": {\n    "_id": "65a8e1b2c3d4e5f6a7b8c9d0",\n    "fName": ["Rahul"],\n    "lName": ["Sharma"],\n    "phone": ["9876543210"],\n    "role": "user",\n    "userNo": 1001,\n    "profileImage": ["https://ik.imagekit.io/..."],\n    "isVerified": true,\n    "status": "Active"\n  }\n}',
    ),
    ApiEndpoint(
      index: 12,
      method: 'PUT',
      path: '/api/user/updateUser',
      category: 'User & Auth',
      title: 'Update User Profile',
      description: 'Updates personal information, address, occupation, and profile images.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      requestBody: 'Form Data:\n  fName: "Rahul"\n  lName: "Sharma"\n  city: "Ahmedabad"\n  state: "Gujarat"\n  profileImage: <file>',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "User profile updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 13,
      method: 'PUT',
      path: '/api/user/update-device-token',
      category: 'User & Auth',
      title: 'Update FCM Device Token',
      description: 'Registers FCM push notification device token for user.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "deviceToken": "fK9s2...device_token_string"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Device token updated"\n}',
    ),
    ApiEndpoint(
      index: 14,
      method: 'GET',
      path: '/api/user/categories',
      category: 'User & Auth',
      title: 'Public User Categories',
      description: 'Retrieves public user categories list for registration dropdown.',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "data": [\n    {\n      "_id": "65b1...",\n      "categoryKey": "dealer",\n      "label": "Authorized Dealer",\n      "requiresAdminVerification": true\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 15,
      method: 'GET',
      path: '/api/user/permissions',
      category: 'User & Auth',
      title: 'User Category Permissions',
      description: 'Returns read/write permission category lists for current authenticated user.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "read": ["Cars", "Bikes", "Properties"],\n  "write": ["Cars", "Bikes"]\n}',
    ),
    ApiEndpoint(
      index: 16,
      method: 'GET',
      path: '/api/user/allowed-product-types',
      category: 'User & Auth',
      title: 'Allowed Product Types for User',
      description: 'Returns allowed product types for posting new listings based on user category permissions.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "allowedProductTypes": ["65a8e...", "65a8f..."]\n}',
    ),

    // ── PRODUCTS & CATALOG ─────────────────────────────────────────────────────
    ApiEndpoint(
      index: 17,
      method: 'GET',
      path: '/api/products/get-product',
      category: 'Products',
      title: 'Get All Products (Feed / Filtered)',
      description: 'Returns paginated products filtered by category, location, price, and dynamic specs.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'page': '1', 'limit': '20', 'category': 'Car', 'city': 'Ahmedabad'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "total": 45,\n  "page": 1,\n  "products": [\n    {\n      "_id": "65a91...",\n      "title": "Honda City 2022 VX",\n      "price": 850000,\n      "categories": "Car",\n      "images": ["https://ik.imagekit.io/..."],\n      "location": { "type": "Point", "coordinates": [72.57, 23.02] },\n      "cityLatest": "Ahmedabad",\n      "createdAt": "2026-08-30T10:00:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 18,
      method: 'GET',
      path: '/api/products/get-product-by-id',
      category: 'Products',
      title: 'Get Product Details by ID',
      description: 'Retrieves complete product specification, seller details, signed images, and view count.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'id': '65a91...'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "product": {\n    "_id": "65a91...",\n    "title": "Honda City 2022 VX",\n    "description": "Single owner, mint condition",\n    "price": 850000,\n    "specs": { "fuel": "Petrol", "km_driven": 25000, "transmission": "Manual" },\n    "images": ["https://ik.imagekit.io/..."],\n    "user": { "_id": "...", "fName": ["Rahul"], "phone": ["9876543210"] }\n  }\n}',
    ),
    ApiEndpoint(
      index: 19,
      method: 'POST',
      path: '/api/products/add',
      category: 'Products',
      title: 'Add New Product Listing',
      description: 'Publishes a new classified product with up to 10 photos and dynamic form specs.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      requestBody: 'Form Data:\n  title: "Honda City 2022"\n  description: "Well maintained"\n  price: 850000\n  categories: "Car"\n  productType: "65a8e..."\n  subProductType: "65a8f..."\n  specs: JSON.stringify({ fuel: "Petrol", year: 2022 })\n  latitude: 23.0225\n  longitude: 72.5714\n  cityLatest: "Ahmedabad"\n  images: [<file1>, <file2>]',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Product created successfully",\n  "productId": "65a91..."\n}',
    ),
    ApiEndpoint(
      index: 20,
      method: 'PUT',
      path: '/api/products/update',
      category: 'Products',
      title: 'Update Product Listing',
      description: 'Updates product title, price, specs, location, and adds/replaces photos.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      requestBody: 'Form Data:\n  productId: "65a91..."\n  price: 820000\n  description: "Price reduced"',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Product updated successfully"\n}',
    ),
    ApiEndpoint(
      index: 21,
      method: 'DELETE',
      path: '/api/products/softDelete/:productId/:productType',
      category: 'Products',
      title: 'Soft Delete Product',
      description: 'Marks a product listing as deleted.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'productId': '65a91...', 'productType': 'Car'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Product deleted successfully"\n}',
    ),
    ApiEndpoint(
      index: 22,
      method: 'POST',
      path: '/api/products/favorites',
      category: 'Products',
      title: 'Toggle Favorite Product',
      description: 'Adds or removes a product from the user favorite list.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "productId": "65a91...",\n  "modelName": "Car"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Product added to favorites"\n}',
    ),
    ApiEndpoint(
      index: 23,
      method: 'GET',
      path: '/api/products/getFavoriteProduct/:userId',
      category: 'Products',
      title: 'Get User Favorite Products',
      description: 'Returns all favorite listings for specified user.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'userId': '65a8e...'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "favorites": [\n    { "_id": "65a91...", "title": "Honda City 2022", "price": 850000 }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 24,
      method: 'GET',
      path: '/api/products/form-metadata',
      category: 'Products',
      title: 'Get Dynamic Form Metadata',
      description: 'Fetches schema, input fields, dropdown options, and validation rules for category posting forms.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'productType': '65a8e...', 'subProductType': '65a8f...'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "fields": [\n    {\n      "key": "fuel_type",\n      "label": "Fuel Type",\n      "type": "dropdown",\n      "options": [\n        { "label": "Petrol", "value": "petrol" },\n        { "label": "Diesel", "value": "diesel" }\n      ],\n      "isOptional": false\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 25,
      method: 'POST',
      path: '/api/products/track-product-view',
      category: 'Products',
      title: 'Track Product View',
      description: 'Increments unique view counter for a product listing.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "productId": "65a91..."\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "views": 42\n}',
    ),

    // ── BRANDS & MODELS ────────────────────────────────────────────────────────
    ApiEndpoint(
      index: 26,
      method: 'GET',
      path: '/api/brands',
      category: 'Brands & Models',
      title: 'Get Brands for Product Type',
      description: 'Returns list of vehicle or electronics brands for dynamic cascading selectors.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'productType': 'car'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "brands": ["Honda", "Hyundai", "Maruti Suzuki", "Tata", "Toyota"]\n}',
    ),
    ApiEndpoint(
      index: 27,
      method: 'GET',
      path: '/api/brands/:productType/:brand/models',
      category: 'Brands & Models',
      title: 'Get Models for Brand',
      description: 'Returns all models belonging to a specific brand.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'productType': 'car', 'brand': 'Honda'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "brand": "Honda",\n  "models": ["City", "Civic", "Amaze", "Elevate", "Jazz"]\n}',
    ),

    // ── REAL-TIME CHAT & MESSAGING ─────────────────────────────────────────────
    ApiEndpoint(
      index: 28,
      method: 'POST',
      path: '/api/chat/fetch-exsisting-conversationId',
      category: 'Chat & Messaging',
      title: 'Create or Fetch Conversation',
      description: 'Creates a new 1-on-1 buyer-seller conversation or returns existing conversation ID.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "sellerId": "65a8e1b2c3d4e5f6a7b8c9d0",\n  "productId": "65a91b2c3d4e5f6a7b8c9d11"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "conversationId": "65b21..."\n}',
    ),
    ApiEndpoint(
      index: 29,
      method: 'POST',
      path: '/api/chat/send-message',
      category: 'Chat & Messaging',
      title: 'Send Text Chat Message',
      description: 'Sends text message in a conversation and emits real-time WebSocket event.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "chatId": "65b21...",\n  "content": "Hi, is this still available?",\n  "type": "text",\n  "clientMessageId": "uuid-v4-1234"\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": {\n    "_id": "65b22...",\n    "chatId": "65b21...",\n    "senderId": "65a8e...",\n    "content": "Hi, is this still available?",\n    "status": "sent",\n    "createdAt": "2026-08-30T11:00:00.000Z"\n  }\n}',
    ),
    ApiEndpoint(
      index: 30,
      method: 'POST',
      path: '/api/chat/sent-image',
      category: 'Chat & Messaging',
      title: 'Send Image Chat Message (Multipart)',
      description: 'Uploads and sends photo attachment in chat with real-time push notification.',
      requiresAuth: true,
      isMultipart: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'multipart/form-data'},
      requestBody: 'Form Data:\n  chatId: "65b21..."\n  image: <file>\n  clientMessageId: "uuid-img-123"',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": {\n    "_id": "65b23...",\n    "content": "https://ik.imagekit.io/...",\n    "type": "image"\n  }\n}',
    ),
    ApiEndpoint(
      index: 31,
      method: 'GET',
      path: '/api/chat/get-all-messages/:conversationId',
      category: 'Chat & Messaging',
      title: 'Get Conversation Messages',
      description: 'Fetches full chat history for a conversation with pagination.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'conversationId': '65b21...'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "messages": [\n    {\n      "_id": "65b22...",\n      "content": "Hi, is this available?",\n      "status": "read"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 32,
      method: 'GET',
      path: '/api/chat/get-all-conversations/:userId',
      category: 'Chat & Messaging',
      title: 'Get User Conversations List',
      description: 'Retrieves all active conversation threads for inbox with last message and unread count.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'userId': '65a8e...'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "conversations": [\n    {\n      "_id": "65b21...",\n      "participants": ["..."],\n      "lastMessage": "Hello",\n      "updatedAt": "2026-08-30T11:30:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 33,
      method: 'PUT',
      path: '/api/chat/update-message-status',
      category: 'Chat & Messaging',
      title: 'Mark Messages as Read',
      description: 'Updates message delivery/read receipts across conversation.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "chatId": "65b21...",\n  "status": "read"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Messages marked as read"\n}',
    ),
    ApiEndpoint(
      index: 34,
      method: 'GET',
      path: '/api/chat/unread_message_count',
      category: 'Chat & Messaging',
      title: 'Get Unread Messages Count',
      description: 'Returns total unread chat message badge count for user.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "unreadCount": 3\n}',
    ),

    // ── HOME FEED & BANNERS ────────────────────────────────────────────────────
    ApiEndpoint(
      index: 35,
      method: 'GET',
      path: '/api/home/content',
      category: 'Home & Feed',
      title: 'Get Home Content & Active Banners',
      description: 'Returns active promotional banners, featured categories, and trending products based on user location and permissions.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      queryParams: {'city': 'Ahmedabad', 'state': 'Gujarat'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "banners": [\n    {\n      "_id": "65c1...",\n      "imageUrl": "https://ik.imagekit.io/...",\n      "actionType": "CATEGORY",\n      "actionData": "Car"\n    }\n  ],\n  "categories": ["Car", "Bike", "Property"]\n}',
    ),
    ApiEndpoint(
      index: 36,
      method: 'POST',
      path: '/api/home/banner/:bannerId/click',
      category: 'Home & Feed',
      title: 'Track Banner Click',
      description: 'Increments banner analytics click count.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'bannerId': '65c1...'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Click recorded"\n}',
    ),

    // ── SUPPORT & HELP DESK ────────────────────────────────────────────────────
    ApiEndpoint(
      index: 37,
      method: 'POST',
      path: '/api/support/create-get-chat',
      category: 'Support & Helpdesk',
      title: 'Create or Get Support Ticket Chat',
      description: 'Opens or returns active support thread between user and customer service.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "supportChat": {\n    "_id": "65d1...",\n    "userId": "65a8e...",\n    "status": "open"\n  }\n}',
    ),
    ApiEndpoint(
      index: 38,
      method: 'POST',
      path: '/api/support/send-message',
      category: 'Support & Helpdesk',
      title: 'Send Support Message',
      description: 'Sends message or photo attachment to support staff.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "chatId": "65d1...",\n  "content": "Need help verifying my account",\n  "type": "text"\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Support message sent"\n}',
    ),
    ApiEndpoint(
      index: 39,
      method: 'GET',
      path: '/api/support/get-messages/:userId',
      category: 'Support & Helpdesk',
      title: 'Get Support Thread Messages',
      description: 'Retrieves all support messages for a user ticket.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      pathParams: {'userId': '65a8e...'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "messages": [\n    {\n      "_id": "65d2...",\n      "senderRole": "user",\n      "content": "Need help with account"\n    }\n  ]\n}',
    ),

    // ── OTP & PASSWORD MANAGEMENT ──────────────────────────────────────────────
    ApiEndpoint(
      index: 40,
      method: 'POST',
      path: '/api/otp/forgot-password',
      category: 'OTP & Password',
      title: 'Forgot Password (Send OTP)',
      description: 'Dispatches OTP via Fast2SMS/MSG91 to registered mobile number for password recovery.',
      requestBody: '{\n  "phone": "9876543210"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP sent successfully to 9876543210"\n}',
    ),
    ApiEndpoint(
      index: 41,
      method: 'POST',
      path: '/api/otp/verify-otp',
      category: 'OTP & Password',
      title: 'Verify Password Reset OTP',
      description: 'Verifies recovery OTP code.',
      requestBody: '{\n  "phone": "9876543210",\n  "otp": "782190"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "OTP verified"\n}',
    ),
    ApiEndpoint(
      index: 42,
      method: 'POST',
      path: '/api/otp/change-password',
      category: 'OTP & Password',
      title: 'Change Password via Recovery Token',
      description: 'Updates account password with recovery proof.',
      requestBody: '{\n  "phone": "9876543210",\n  "password": "brandNewPassword2026!"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Password changed successfully"\n}',
    ),

    // ── LOCATION SERVICES ──────────────────────────────────────────────────────
    ApiEndpoint(
      index: 43,
      method: 'GET',
      path: '/api/location/locations',
      category: 'Locations',
      title: 'Search Locations & Pincodes',
      description: 'Returns matching postal codes, districts, subdistricts, and states.',
      queryParams: {'search': 'Ahmedabad', 'pincode': '380001'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "locations": [\n    {\n      "Postal_Code": "380001",\n      "Location_Name": "Ahmedabad",\n      "District": "Ahmedabad",\n      "State": "Gujarat"\n    }\n  ]\n}',
    ),

    // ── APP VERSION & UPDATES ──────────────────────────────────────────────────
    ApiEndpoint(
      index: 44,
      method: 'GET',
      path: '/api/app-version/latest',
      category: 'App Updates',
      title: 'Get Latest App Version',
      description: 'Checks for mandatory Flutter mobile app update APK releases.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "data": {\n    "version": "1.0.8",\n    "versionName": "v1.0.8",\n    "apkLink": "https://storage.googleapis.com/.../app.apk",\n    "changes": "Enhanced speed & performance"\n  }\n}',
    ),

    // ── ABOUT US & GUIDE VIDEOS ────────────────────────────────────────────────
    ApiEndpoint(
      index: 45,
      method: 'GET',
      path: '/api/about-us',
      category: 'About & Guide',
      title: 'Get About Us Information',
      description: 'Returns company mission, story, stats, values, and tagline.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "data": {\n    "our_mission": "Best verified marketplace",\n    "name": "Classicale",\n    "happy_customer": 15000\n  }\n}',
    ),
    ApiEndpoint(
      index: 46,
      method: 'GET',
      path: '/api/app-guide-video/get-visible-video',
      category: 'About & Guide',
      title: 'Get Active App Guide Video',
      description: 'Returns streaming URL for the active app tutorial video.',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "video": {\n    "title": "How to post an ad",\n    "videoName": "guide_01.mp4",\n    "streamUrl": "/public/videos/app-guide/guide_01.mp4"\n  }\n}',
    ),

    // ── FEEDBACK & FEATURE REQUESTS ────────────────────────────────────────────
    ApiEndpoint(
      index: 47,
      method: 'POST',
      path: '/api/feedback',
      category: 'Feedback',
      title: 'Submit Feature Request / Feedback',
      description: 'Submits user feedback or feature proposal.',
      requiresAuth: true,
      headers: {'Authorization': 'Bearer <token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "title": "Dark Mode Support",\n  "description": "Please add OLED dark mode theme."\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Feedback submitted successfully"\n}',
    ),

    // ── ADMIN PANEL & RBAC MANAGEMENT ──────────────────────────────────────────
    ApiEndpoint(
      index: 48,
      method: 'POST',
      path: '/api/admin/login',
      category: 'Admin & RBAC',
      title: 'Admin Login',
      description: 'Authenticates superadmin or subadmin and returns admin JWT token with role claims.',
      requestBody: '{\n  "email": "superadmin@classical.com",\n  "password": "SuperSecretAdminPassword!2026"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6...",\n  "admin": {\n    "_id": "65e1...",\n    "username": "Super Admin",\n    "email": "superadmin@classical.com",\n    "role": "superadmin"\n  }\n}',
    ),
    ApiEndpoint(
      index: 49,
      method: 'GET',
      path: '/api/admin/get_all_user',
      category: 'Admin & RBAC',
      title: 'Get All Users (Admin Table)',
      description: 'Returns paginated user list with status, verification, aadhaar images, and phone numbers.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      queryParams: {'page': '1', 'limit': '50', 'status': 'Active', 'search': 'Rahul'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "total": 1200,\n  "users": [\n    {\n      "_id": "65a8e...",\n      "fName": ["Rahul"],\n      "phone": ["9876543210"],\n      "isVerified": true,\n      "status": "Active"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 50,
      method: 'POST',
      path: '/api/admin/verify_by_admin',
      category: 'Admin & RBAC',
      title: 'Verify / Reject User by Admin',
      description: 'Approves user Aadhaar verification or rejects with reason.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "userId": "65a8e...",\n  "isVerified": true,\n  "aadhaarRejectionReason": ""\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "User verification status updated"\n}',
    ),
    ApiEndpoint(
      index: 51,
      method: 'POST',
      path: '/api/admin/user_active_inActive',
      category: 'Admin & RBAC',
      title: 'Toggle User Active / Inactive Status',
      description: 'Activates or suspends a user account.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "userId": "65a8e...",\n  "status": "Active"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "User status updated"\n}',
    ),
    ApiEndpoint(
      index: 52,
      method: 'POST',
      path: '/api/admin/access_pin',
      category: 'Admin & RBAC',
      title: 'Assign Access Pin to User',
      description: 'Generates and assigns secret PIN to user for special category permissions.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "userId": "65a8e...",\n  "pin": "VIP8899"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Access PIN assigned successfully"\n}',
    ),
    ApiEndpoint(
      index: 53,
      method: 'GET',
      path: '/api/admin/subadmin/all',
      category: 'Admin & RBAC',
      title: 'Get All Subadmins',
      description: 'Lists all subadmin staff members.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "subadmins": [\n    {\n      "_id": "65f1...",\n      "username": "Moderator 1",\n      "email": "mod1@classical.com",\n      "role": "subadmin"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 54,
      method: 'POST',
      path: '/api/admin/subadmin/create',
      category: 'Admin & RBAC',
      title: 'Create Subadmin Account',
      description: 'Provisions new subadmin user with specific module permissions.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "username": "Moderator 2",\n  "email": "mod2@classical.com",\n  "password": "ModPassword123!",\n  "permissions": {\n    "product": { "read": true, "write": true },\n    "user": { "read": true, "write": false }\n  }\n}',
      responseStatus: 201,
      responseBody: '{\n  "success": true,\n  "message": "Subadmin created successfully"\n}',
    ),
    ApiEndpoint(
      index: 55,
      method: 'GET',
      path: '/api/admin/permissions',
      category: 'Admin & RBAC',
      title: 'Get Admin Permissions',
      description: 'Returns RBAC granular permissions matrix for logged-in admin.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "permissions": {\n    "product": { "read": true, "write": true, "assign_pin": false },\n    "user": { "read": true, "write": false, "assign_pin": true }\n  }\n}',
    ),
    ApiEndpoint(
      index: 56,
      method: 'GET',
      path: '/api/admin/audit-logs',
      category: 'Admin & RBAC',
      title: 'Get Admin Audit Logs',
      description: 'Retrieves audit logs tracking every admin action, endpoint, and modification.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      queryParams: {'page': '1', 'limit': '50', 'action': 'UPDATE'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "logs": [\n    {\n      "_id": "65g1...",\n      "adminUsername": "superadmin",\n      "action": "VERIFY_USER",\n      "endpoint": "/api/admin/verify_by_admin",\n      "status": "SUCCESS",\n      "createdAt": "2026-08-31T07:00:00.000Z"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 57,
      method: 'GET',
      path: '/api/admin/report_product',
      category: 'Admin & RBAC',
      title: 'Get Product Moderation Reports',
      description: 'Lists all user-reported product listings requiring admin review.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>'},
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "reports": [\n    {\n      "_id": "65h1...",\n      "productId": "65a91...",\n      "description": "Suspicious fraudulent ad",\n      "status": "pending"\n    }\n  ]\n}',
    ),
    ApiEndpoint(
      index: 58,
      method: 'PUT',
      path: '/api/admin/update-report-status',
      category: 'Admin & RBAC',
      title: 'Resolve or Decline Product Report',
      description: 'Updates status of moderation report to resolve or decline.',
      requiresAdmin: true,
      headers: {'Authorization': 'Bearer <admin_token>', 'Content-Type': 'application/json'},
      requestBody: '{\n  "reportId": "65h1...",\n  "status": "resolve",\n  "note": "Product removed due to policy violation"\n}',
      responseStatus: 200,
      responseBody: '{\n  "success": true,\n  "message": "Report status updated"\n}',
    ),
  ];
}
